name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) ソースをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v4

      # 2) Node.js と pnpm キャッシュセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "pnpm"

      # 3) Corepack を有効化して pnpm を準備
      - name: Enable Corepack
        run: corepack enable

      - name: Activate pnpm
        run: corepack prepare pnpm@latest --activate

      # 4) 依存パッケージをインストール
      - name: Install dependencies
        run: pnpm install

      # 5) ビルド
      - name: Build
        run: pnpm run build

      # 6) Firebase Hosting にデプロイ
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LEARNING_FIREBASE_2F4F5 }}
          channelId: live
          projectId: learning-firebase-2f4f5
