# .github/workflows/firebase-hosting-pull-request.yml

name: Deploy to Firebase Hosting on PR

on: pull_request

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    # 同一リポジトリ内のPRのみ実行
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest

    steps:
      # 1) ソースをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v4

      # 2) Node.js と pnpm キャッシュのセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "pnpm"

      # 3) pnpm CLI をインストール
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      # 4) 依存パッケージをインストール
      - name: Install dependencies
        run: pnpm install

      # 5) ビルド
      - name: Build
        run: pnpm run build

      # 6) Firebase Hosting にプレビューとしてデプロイ
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LEARNING_FIREBASE_2F4F5 }}
          projectId: learning-firebase-2f4f5
